spring.application.name=MyFirstOllama
# LLM for text
spring.ai.ollama.chat.model=gemma3:1b
# LLM for embedding
#spring.ai.ollama.embedding.model=mxbai-embed-large

# LLM support tools, this also works to define the model
#spring.ai.ollama.chat.options.model=lfm2.5-thinking

# Required for RAG agents
spring.ai.vectorstore.pinecone.api-key=xx
spring.ai.vectorstore.pinecone.index-name=myspringaiindex

file.upload.dir=images/uploads
